-- How many times each movie has been rented out

SELECT F.TITLE,
	COUNT(R.RENTAL_ID)
FROM FILM F,
	RENTAL R,
	INVENTORY I
WHERE F.FILM_ID = I.FILM_ID
	AND I.INVENTORY_ID = R.INVENTORY_ID
GROUP BY 1
ORDER by count DESC;