-- How many times each movie has been rented out

SELECT F.TITLE,
	COUNT(R.RENTAL_ID)
FROM FILM F,
	RENTAL R,
	INVENTORY I
WHERE F.FILM_ID = I.FILM_ID
	AND I.INVENTORY_ID = R.INVENTORY_ID
GROUP BY 1
ORDER BY COUNT DESC;

-- Revenue by different Store ID's

SELECT I.STORE_ID AS "Store ID",
	SUM(P.AMOUNT) AS REVENUE
FROM INVENTORY I,
	PAYMENT P,
	RENTAL R
WHERE P.RENTAL_ID = R.RENTAL_ID
	AND R.INVENTORY_ID = I.INVENTORY_ID
GROUP BY 1
ORDER BY 2 DESC ;

-- Users who have rented out at least 5 times

SELECT R.CUSTOMER_ID AS CUSTOMER,
	COUNT(R.RENTAL_ID) AS "Number_of_Rentals"
FROM RENTAL R
GROUP BY 1
HAVING COUNT(R.RENTAL_ID) >= 5
ORDER BY "Number_of_Rentals" ASC ;